#
# /etc/pacman.conf used while BUILDING the Velocity ISO.
# The [velocity] repo points at the local package repo produced by
# scripts/build-iso.sh (it contains velocity-tools).
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 8
Color
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[velocity]
SigLevel = Optional TrustAll
Server = file:///velocity-repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
