# Velocity Linux live shell (zsh)
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt autocd share_history hist_ignore_dups

autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

# Velocity aliases
alias ls='eza --icons --group-directories-first'
alias ll='eza -la --icons --group-directories-first'
alias cat='bat --paging=never'
alias grep='rg'
alias install='velocity-install'
alias vl='velocity'

# Prompt
export STARSHIP_CONFIG=/etc/velocity/starship.toml
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# First shell on tty1 shows the welcome
if [[ "$(tty)" == /dev/tty1 && -z "${VELOCITY_WELCOMED:-}" ]]; then
  export VELOCITY_WELCOMED=1
  /usr/local/bin/velocity-live-init
fi
