# Velocity · kitty
include theme.conf

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.5

window_padding_width 12
background_opacity   0.92
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
cursor_shape beam
cursor_blink_interval 0.6
scrollback_lines 10000
url_style curly

tab_bar_style powerline
tab_powerline_style slanted
