# Velocity · Night
foreground            #e6e6f0
background            #0b0b12
selection_foreground  #0b0b12
selection_background  #22d3ee
cursor                #7c5cff
cursor_text_color     #0b0b12
url_color             #22d3ee
active_border_color   #7c5cff
inactive_border_color #2a2a3a
active_tab_foreground   #0b0b12
active_tab_background   #7c5cff
inactive_tab_foreground #8c8ca0
inactive_tab_background #14141f

color0  #14141f
color8  #2a2a3a
color1  #f38ba8
color9  #f38ba8
color2  #a6e3a1
color10 #a6e3a1
color3  #f9e2af
color11 #f9e2af
color4  #7c5cff
color12 #9d85ff
color5  #cba6f7
color13 #cba6f7
color6  #22d3ee
color14 #67e8f9
color7  #e6e6f0
color15 #ffffff
