#
# /etc/pacman.conf inside the Velocity live session and installed system.
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 8
Color
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
